sudo: required
services:
  - docker

before_install:
  - docker build -t parr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker-react-env"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-eu-west-1-189655651773"
  bucket_path: "Docker-react-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"